# Generated by Django 3.0.6 on 2020-06-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200608_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'ordering': ['name']},
        ),
    ]
