# Generated by Django 3.0.6 on 2020-06-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200608_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'ordering': ['listing_name']},
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='description',
            new_name='listing_description',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='image',
            new_name='listing_image',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='name',
            new_name='listing_name',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='price',
            new_name='listing_price',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
        migrations.AddField(
            model_name='listings',
            name='listing_brand',
            field=models.CharField(choices=[('', 'See all'), ('toyota', 'Toyota'), ('nissan', 'Nissan'), ('honda', 'Honda')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='listings',
            name='listing_category',
            field=models.CharField(choices=[('', 'See all'), ('engines', 'Engines'), ('gearboxes', 'Gear Boxes'), ('lamps', 'Lamps'), ('Radiators', 'radiators'), ('bumpers', 'Bumpers')], default='', max_length=15),
        ),
    ]
