# Generated by Django 3.0.6 on 2020-06-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20200614_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
