# Generated by Django 3.0.6 on 2020-06-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_category_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_category',
            field=models.CharField(choices=[('', 'See all'), ('engines', 'Engines'), ('gearboxes', 'Gear Boxes'), ('lamps', 'Lamps'), ('Radiators', 'radiators'), ('bumpers', 'Bumpers')], default='', max_length=15),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
