# Generated by Django 3.0.6 on 2020-06-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20200614_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
