# Generated by Django 3.0.6 on 2020-06-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20200614_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('engines', 'Engines'), ('gearboxes', 'Gear Boxes'), ('lamps', 'Lamps'), ('Radiators', 'radiators'), ('bumpers', 'Bumpers')], max_length=15),
        ),
    ]
