# Generated by Django 3.0.6 on 2020-06-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20200614_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Engines', 'engines'), ('Gear Boxes', 'gearboxes'), ('Lamps', 'lamps'), ('Radiators', 'radiators'), ('Bumpers', 'bumpers')], max_length=15),
        ),
    ]
