# Generated by Django 3.0.6 on 2020-06-14 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20200614_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('toyota', 'Toyota'), ('nissan', 'Nissan'), ('honda', 'Honda')], max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Brand'),
        ),
    ]
