# Generated by Django 3.0.6 on 2020-06-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20200614_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(choices=[('Toyota', 'toyota'), ('Nissan', 'nissan'), ('Honda', 'honda')], max_length=15),
        ),
    ]
