# Generated by Django 3.0.6 on 2020-06-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20200614_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_price',
            new_name='price',
        ),
    ]
