# Generated by Django 3.0.6 on 2020-06-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20200616_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='listing_price',
        ),
    ]
