# Generated by Django 3.0.6 on 2020-06-26 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20200616_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(20.0)]),
        ),
    ]
