# Generated by Django 3.0.6 on 2020-06-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='street_address2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
