# Generated by Django 3.0.6 on 2020-06-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200606_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_name',
            field=models.CharField(max_length=50),
        ),
    ]
