# Generated by Django 3.0.6 on 2020-06-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200618_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='eircode',
            new_name='postcode',
        ),
    ]
