# Generated by Django 3.0.6 on 2020-06-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200620_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='date',
        ),
    ]
