# Generated by Django 3.0.6 on 2020-06-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200625_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
