# Generated by Django 3.0.6 on 2020-06-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_orderlineitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
